- test/index.js
Added in some initial tests, check them out again!!!!!!
> Add initial tests

- lib/index.js
- main.bundle.js
- package.json
up next! all the other functionality of the complete button
> complete button grays out task

- lib/index.js
you can now switch between 5 levels of importance. filtering coming soon
> importance levels added

- css/styles.css
- index.html
- lib/index.js
- main.bundle.js
- test.bundle.js
- test/index.js
Finished up the character count section, and the feature to disable the button when over 120. The hype is real.
> Jb char count

- css/styles.css
- index.html
- lib/index.js
all those pesky ideas have no become tasks for us 2Do... fam.
> converted ideas to tasks

- lib/index.js
but the damn box don't stay gray tho
> completed state of tasks persist in local storage

- index.html
- lib/index.js
- main.bundle.js
- test.bundle.js
add a 'show all' button that reveals older ideas on click.
> only show 10 most recent todos on page load

- lib/index.js
- main.bundle.js
- test.bundle.js
- test/index.js
Wrote some shitty tests we probably can't make break, but who knows! Now we need to refactor index.js and pull it apart into multiple files so we can actually test them.
> Write more basic tests

- index.html
- lib/index.js
completed tasks do not load on pageload, repopulate at top of list when"show completed" button is clicked. still not gray tho. maybe work on that?
> show completed button works

- test/index.js
- test/test.js
in terminal, run 'npm install selenium-webdriver'
then 'npm test' will work and run unit tests from the test/index.js file and dom tests from test/test.js
> testing suite is running boiiii

- index.html
- package.json
- test/index.js
- test/test.js
make sure to spin up server in one terminal window and then run tests in another
> selenium tests now work

- css/styles.css
- lib/index.js
- main.bundle.js
- test.bundle.js
I nested  a <p> class in the button, and then set their opacity to 0. Now I just need to figure out the form fields, and we're done w/ aXe.
> Complete button label aXe issues

- lib/index.js
- test/index.js
- test/test.js
> Added selenium tests for input fields, save button, up&down votes

- css/styles.css
- index.html
Accessibility is done. Now on to tests. It's happening.
> Jb accessibility

- index.html
- lib/index.js
that button sucked anyway. the new 6 button filter system is way more lit.
> remove 'sort' button, redundant functionality

- lib/index.js
replaced var with let, or const where appropriate. 
replaced all anonymous functions that didn't contain a 'this' with an arrow function.
> begin pivot to es6

- css/styles.css
- index.html
- lib/index.js
Namaste garbage pail recognize garbage pail. Buttons stay where I told em to, and do stuff on hover, and are also still buttons.
> Fix basic CSS issues

- css/styles.css
- lib/index.js
- test/test.js
> Completed card gray state persists on refresh

- css/styles.css
Stupid line was too long. Told it to get back in line.
> Fix bottom border issue on cards

- css/styles.css
- index.html
Fixed some basic crap to make the code look a bit cleaner. No, I didn't do testing.
> Jb final cleanup
